# Transcription settings
transcription:
  service: "whisperx"  # Options: "whisper", "assemblyai"
  whisper:
    model: "tiny"  # Options: "tiny", "base", "small", "medium", "large-v3", "distil-large-v3"
    batch_size: 2 # try 2 for large models, 4 for small/medium for cpu
    device: "cpu"  # Options: "cpu", "cuda"
    language_code: "en"  
    compute_type: "int8" # Options: "int8", "float16", "float32"
  assemblyai:
    language_code: "en"
    model: nano

# OpenAI settings
openai:
  model: "gpt-4.1-mini"  # Corrected model name

# Chunking parameters
chunking:
  chunk_word_target: 500
  max_summary_words: 300
  enable_summary_summarization: true

# Environment file path
env_file: "./config.env"